#!/usr/bin/env bash

# This script applies a curated theme by:
# 1. Extracting colors from the theme's kitty.theme/hypr.theme
# 2. Generating a full Material 3 palette for Quickshell
# 3. Applying the theme to Hyprland, KDE, Kitty and other system components

THEME_PATH=""
IMAGE_PATH=""
MODE="dark"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --theme-path) THEME_PATH="$2"; shift 2 ;;
        --image) IMAGE_PATH="$2"; shift 2 ;;
        --mode) MODE="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# Expand ~ if present
THEME_PATH="${THEME_PATH/#\~/$HOME}"
IMAGE_PATH="${IMAGE_PATH/#\~/$HOME}"

if [[ -z "$THEME_PATH" || ! -d "$THEME_PATH" ]]; then
    echo "Usage: $0 --theme-path <path> [--image <path>] [--mode <dark|light>]"
    exit 1
fi

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_DIR="$XDG_STATE_HOME/quickshell"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHELL_CONFIG_FILE="$XDG_CONFIG_HOME/illogical-impulse/config.json"

# Ensure virtual env is set
if [[ -z "$ILLOGICAL_IMPULSE_VIRTUAL_ENV" ]]; then
    export ILLOGICAL_IMPULSE_VIRTUAL_ENV="$HOME/.local/state/quickshell/.venv"
fi

# 1. Extract colors from theme files
KITTY_THEME="$THEME_PATH/kitty.theme"
HYPR_THEME="$THEME_PATH/hypr.theme"
THEME_JSON="$THEME_PATH/theme.json"

if [[ -f "$THEME_JSON" ]]; then
    echo "Using theme.json for color mapping..."
    HAS_THEME_JSON=true
    ICONS=$(jq -r '.icons // empty' "$THEME_JSON")
else
    PRIMARY_COLOR=$(grep "^active_border_color" "$KITTY_THEME" | awk '{print $2}' | head -n 1)
    if [[ -z "$PRIMARY_COLOR" ]]; then
        PRIMARY_COLOR=$(grep "^color4" "$KITTY_THEME" | awk '{print $2}' | head -n 1)
    fi
    PRIMARY_COLOR=${PRIMARY_COLOR/#\#/}

    BACKGROUND_COLOR=$(grep "^background" "$KITTY_THEME" | awk '{print $2}' | head -n 1)
    BACKGROUND_COLOR=${BACKGROUND_COLOR/#\#/}
    echo "Detected Primary: #$PRIMARY_COLOR, Background: #$BACKGROUND_COLOR"
fi

# 2. Generate Material 3 palette
VENV_PATH=$(eval echo "$ILLOGICAL_IMPULSE_VIRTUAL_ENV")
source "$VENV_PATH/bin/activate" || echo "Warning: Could not activate venv at $VENV_PATH"

if [[ "$HAS_THEME_JSON" == "true" ]]; then
    PRIMARY_COLOR=$(jq -r '.primary' "$THEME_JSON" | sed 's/#//')
    THEME_NAME=$(basename "$THEME_PATH")
    MATUGEN_TYPE="scheme-vibrant"
    if [[ "$THEME_NAME" == "1-Bit" || "$THEME_NAME" == "Graphite Mono" || "$THEME_NAME" == "AbyssGreen" ]]; then
        MATUGEN_TYPE="scheme-monochrome"
    fi
    matugen color hex "$PRIMARY_COLOR" --mode "$MODE" --type "$MATUGEN_TYPE"
    
    COLORS_JSON="$STATE_DIR/user/generated/colors.json"
    jq -s '.[0] * .[1]' "$COLORS_JSON" "$THEME_JSON" > "$COLORS_JSON.tmp" && mv "$COLORS_JSON.tmp" "$COLORS_JSON"
else
    matugen color hex "$PRIMARY_COLOR" --mode "$MODE" --type scheme-vibrant
    
    if [[ -n "$BACKGROUND_COLOR" ]]; then
        COLORS_JSON="$STATE_DIR/user/generated/colors.json"
        if [[ -f "$COLORS_JSON" ]]; then
            jq --arg bg "#$BACKGROUND_COLOR" '
                .background = $bg | 
                .surface = $bg | 
                .surface_container = $bg |
                .surface_container_low = $bg |
                .surface_container_lowest = $bg
            ' "$COLORS_JSON" > "$COLORS_JSON.tmp" && mv "$COLORS_JSON.tmp" "$COLORS_JSON"
        fi
    fi
fi

# 3. Apply the theme to Hyprland
if [[ -f "$HYPR_THEME" ]]; then
    ACTIVE_BORDER=$(grep "col.active_border" "$HYPR_THEME" | cut -d'=' -f2- | xargs)
    INACTIVE_BORDER=$(grep "col.inactive_border" "$HYPR_THEME" | cut -d'=' -f2- | xargs)
    
    if [[ -n "$ACTIVE_BORDER" ]]; then
        cat > "$XDG_CONFIG_HOME/hypr/hyprland/colors.conf" << EOF
# Generated by apply_curated_theme.sh for theme: $(basename "$THEME_PATH")
general {
    col.active_border = $ACTIVE_BORDER
    col.inactive_border = $INACTIVE_BORDER
}
EOF
    fi

    ROUNDING=$(grep "rounding =" "$HYPR_THEME" | cut -d'=' -f2- | head -n 1 | xargs)
    if [[ -n "$ROUNDING" ]]; then
        echo "Detected rounding: $ROUNDING"
        jq --argjson r "$ROUNDING" '.appearance.rounding = $r' "$SHELL_CONFIG_FILE" > "$SHELL_CONFIG_FILE.tmp" && mv "$SHELL_CONFIG_FILE.tmp" "$SHELL_CONFIG_FILE"
    fi
fi

# 4. Update the wallpaper path and active theme
if [[ -n "$IMAGE_PATH" ]]; then
    THEME_NAME=$(basename "$THEME_PATH")
    jq --arg path "$IMAGE_PATH" --arg theme "$THEME_NAME" '.background.wallpaperPath = $path | .background.activeTheme = $theme' "$SHELL_CONFIG_FILE" > "$SHELL_CONFIG_FILE.tmp" && mv "$SHELL_CONFIG_FILE.tmp" "$SHELL_CONFIG_FILE"
    
    # Save last wallpaper as theme logo for the selector
    mkdir -p "$THEME_PATH/logo"
    if [ -f "$IMAGE_PATH" ]; then
        cp "$IMAGE_PATH" "$THEME_PATH/logo/logo_last.png"
    fi

    # Update the KDE wallpaper path file
    KDE_WALLPAPER_PATH="$STATE_DIR/user/generated/wallpaper/path.txt"
    mkdir -p "$(dirname "$KDE_WALLPAPER_PATH")"
    echo "$IMAGE_PATH" > "$KDE_WALLPAPER_PATH"
fi

# 5. Final system-wide application
THEME_NAME=$(basename "$THEME_PATH")
MATUGEN_TYPE="scheme-vibrant"
if [[ "$THEME_NAME" == "1-Bit" || "$THEME_NAME" == "Graphite Mono" || "$THEME_NAME" == "AbyssGreen" ]]; then
    MATUGEN_TYPE="scheme-monochrome"
fi
python3 "$SCRIPT_DIR/generate_colors_material.py" --color "$PRIMARY_COLOR" --mode "$MODE" --scheme "$MATUGEN_TYPE" > "$STATE_DIR/user/generated/material_colors.scss"

python3 "$SCRIPT_DIR/apply_heroic_theme.py" &

mkdir -p "$STATE_DIR"/user/generated/terminal
if [[ -f "$KITTY_THEME" ]]; then
    echo "Applying curated Kitty theme..."
    # 1. Skip the first line ONLY if it's the header line
    # 2. Filter out comments and empty lines
    tail -n +2 "$KITTY_THEME" | grep -v "^#" | sed '/^\s*$/d' | sed 's/^[ \t]*//;s/[ \t]*$//' > "$STATE_DIR/user/generated/terminal/kitty-theme.conf"
    export SKIP_KITTY="true"
    export SKIP_ANYTERM="true"
fi

# Run applycolor.sh (respects SKIP_KITTY/SKIP_ANYTERM)
"$SCRIPT_DIR/applycolor.sh"

# Force KDE colors update
if [[ -f "$VENV_PATH/bin/kde-material-you-colors" ]]; then
    echo "Updating KDE colors with curated primary: #$PRIMARY_COLOR"
    VARIANT=6
    if [[ "$THEME_NAME" == "Graphite Mono" || "$THEME_NAME" == "1-Bit" || "$THEME_NAME" == "AbyssGreen" ]]; then VARIANT=3; fi
    
    KDE_CMD=("$VENV_PATH/bin/kde-material-you-colors" "--color" "#$PRIMARY_COLOR" "--scheme-variant" "$VARIANT")
    
    if [[ -n "$ICONS" ]]; then
        echo "Forcing icon theme: $ICONS"
        KDE_CMD+=("--iconsdark" "$ICONS" "--iconslight" "$ICONS")
    fi
    
    "${KDE_CMD[@]}" > /dev/null 2>&1 &
fi

deactivate
hyprctl reload
kill -SIGUSR1 $(pidof kitty) > /dev/null 2>&1
